/*
==================================================================================================================================
# BENCHMARKING SOMATIC VARIANT CALLERS PIPELINE
==================================================================================================================================
# This script evaluates the performance of different somatic variant callers (LoFreq, VarDict, VarScan2, and Mutect2) by:
# 1. Generating VCF statistics: uses bcftools stats to provide a descriptive overview of the called variants.
# 2. Somatic Benchmarking: uses som.py (from hap.py) to compare "Query" VCFs against a "Truth Set" VCF.
    ${truth_vcf}: path to the "Truth Set" VCF file containing known positives for chromosome 7
    ${test_vcf}: path to the "Query" VCF file generated by the variant caller being evaluated
     -r ${fa_file}: indicates path to chromosome 7 reference FASTA sequence
     -R ${bed_file}: indicates path to bed file with Onco Panel sequenced regions on chromosome 7
     -o ${prefix}: defines the output prefix for the benchmarking results
     -P: enables the generation of precision-recall curves
     --happy-stats: generates additional statistics for benchmarking
     --feature-table generic: creates a feature table for potential machine learning applications
     --af-query "${af_field}": specifies the allele frequency field in the Query VCF
     --af-truth "AF": specifies the allele frequency field in the Truth Set VCF
# 3. Metrics Consolidation: merges performance parameters (Precision, Recall, F1-Score) into a single summary table.
# 4. Quality Control Reporting: generates a MultiQC report for visual comparison across callers.

# For each step, a specific Seqera container (compatible with ARM64 architecture) is used.
# ==================================================================================================================================
*/

nextflow.enable.dsl=2

// Path to the main project directory
params.project = "/Users/nairaramosandres/Benchmarking-Somatic-VariantCallers-ctDNA"
// Path to Chromosome 7 reference FASTA and its corresponding index files
params.genome ="${params.project}/genome/chr7_genome/chr7.fa"
params.genome_index = "${params.project}/genome/chr7_genome/chr7.fa.fai"
// Path to VCFs files from variant callers
params.input_vcfs = "${params.project}/results/Results_Subsample_*/variant_calling/benchmarking_vcf/benchmarking_preprocessed/*.vcf.gz"
// Path to Truth Set VCF file
params.truth = "${params.project}/metadata/truthset_files/TruthSet_chr7/KnownPositives_chr7_rename.vcf.gz"
// Path to Onco Panel bed files from Chromosome 7
params.bed = "${params.project}/metadata/bed_files/chr7_target.bed.gz"
// Path to the main results directory
params.outdir = "${params.project}/results"

/*
 * Workflow Processes
 */

// 1. Generating VCF statistics with bcftools stats
process vcfStats {

    tag "Generating VCF statistics for ${group_id}"
    container 'community.wave.seqera.io/library/bcftools:1.23.1--15a480527db1d585'
    publishDir "${params.outdir}/Results_Subsample_*/variant_calling/benchmarking_results/${group_id}/vcf_stats", mode: 'copy'

    input:
    tuple val(subsample_id), val(group_id), val(vc_name), path(vcf)

    output:
    tuple val(subsample_id), val(group_id), path("${vc_name}.stats.txt"), emit: stats

    script:
    """
    bcftools stats ${vcf} > ${vc_name}.stats.txt
    """
}

// 2. Somatic Benchmarking with som.py
process sompyBenchmark {

    tag "Creating Benchmarking Report for ${vc_name} using som.py"
    container 'community.wave.seqera.io/library/hap.py:0.3.15--cc9c0286f5a6f629'
    containerOptions "--platform linux/amd64"
    publishDir "${params.outdir}/Results_Subsample_*/variant_calling/benchmarking_results/${group_id}/sompy_results", mode: 'copy'
    
    input:
    tuple val(subsample_id), val(group_id), val(vc_name), path(test_vcf)
    path truth_vcf
    path truth_tbi
    path fa_file
    path fa_index
    path bed_file

    output:
    tuple val(subsample_id), val(group_id), path("*.stats.csv"), emit: stats
    tuple val(subsample_id), val(group_id), path("*.summary.csv"), emit: summary
    path("*.features.csv"), emit: features
    tuple val(subsample_id), val(group_id), path("${vc_name}_benchmarking.tp.vcf.gz"), emit: tp_vcf, optional: true
    tuple val(subsample_id), val(group_id), path("${vc_name}_benchmarking.fp.vcf.gz"), emit: fp_vcf, optional: true

    script:
    // Define the output prefix for the benchmarking results
    def prefix = "${vc_name}_benchmarking"
    // Determine the appropriate AF field based on the variant caller (e.g., VarScan uses FREQ, others use AF)
    def af_field = (vc_name.contains("varscan")) ? "FREQ" : "AF"
    """
    # Index the test VCF to allow som.py to read it
    bcftools index -t ${test_vcf}
    export HGREF=${fa_file}
    # Benchmarking with som.py
    som.py \\
        ${truth_vcf} \\
        ${test_vcf} \\
        -r ${fa_file} \\
        -R ${bed_file} \\
        -o "${prefix}" \\
        -P \\
        --happy-stats \\
        --feature-table generic \\
        --af-query "${af_field}" \\
        --af-truth "AF"
    """
}

// 3. Merging performance parameters into a single summary table
process mergeMetrics {

    tag "merging Benchmarking Metrics for ${subsample_id}"
    publishDir "${params.outdir}/Results_Subsample_*/variant_calling/benchmarking_results/${group_id}/merged_parameters", mode: 'copy'
    
    input:
    tuple val(subsample_id), val(group_id), path(summary_files)

    output:
    path "parameters_summary.csv"

    script:
    """
    # Create the header for the summary CSV file
    echo "CALLER,SUBSAMPLE,GROUP,TRUTH_TOTAL,QUERY_TOTAL,TP,FP,FN,RECALL,PRECISION,F1" > parameters_summary.csv
    
    # Iterate over each summary file, extract relevant metrics and append to the summary CSV
    for f in ${summary_files}; do
        caller=\$(basename \$f | cut -d'_' -f9)
        line=\$(grep ",PASS," \$f | awk -F',' '{print \$4","\$7","\$5","\$8","\$6","\$11","\$12","\$14}')
        echo "\$caller,${subsample_id},${group_id},\$line" >> parameters_summary.csv
    done
    """
}

// 4. Generating MultiQC reports for visual comparison across callers
process multiQCreports {

    tag "MultiQC reports for ${subsample_id}"
    container 'multiqc/multiqc:latest'
    publishDir "${params.outdir}/Results_Subsample_*/variant_calling/benchmarking_results/${group_id}/multiQC_reports", mode: 'copy'

    input:
    tuple val(subsample_id), val(group_id), path(summaries), path(stats)

    output:
    path "multiqc_report.html"

    script:
    """
    multiqc .
    """
}

/*
 * Workflow
 */

workflow {

    // Channel for Chromosome 7 reference FASTA and all index files
    genome_ch = Channel.fromPath(params.genome).collect()
    genome_index_ch = Channel.fromPath(params.genome_index).collect()
    // Channel for Onco Panel BED file
    bed_ch = Channel.fromPath(params.bed).collect()
    // Channel for Truth Set VCF and its index
    truth_vcf_ch = Channel.fromPath(params.truth).collect()
    truth_tbi_ch = Channel.fromPath("${params.truth}.tbi").collect()

    // Channel for VCF files from variant callers, extracting Subsample ID and Group ID (B-D or B-E)
    test_vcf_ch = Channel.fromPath(params.input_vcfs, checkIfExists: true)
        .map { file -> 
            def sub_id = file.parent.parent.parent.parent.name.replace("Results_Subsample_", "S")
            def group_id = (file.name.contains("_D_") || file.name.contains("_vs_D_")) ? "B_D" : "B_E"
            def vc_name  = file.baseName.replaceAll(".vcf.gz", "").replaceAll(".vcf", "")
            return tuple(sub_id, group_id, vc_name, file)
        }
    
    // Processes execution
    vcfStats(test_vcf_ch)
    sompyBenchmark(test_vcf_ch, truth_vcf_ch, truth_tbi_ch, genome_ch, genome_index_ch, bed_ch)
    // Merging metrics and generating MultiQC reports for each Subsample and Group
    metrics_in = sompyBenchmark.out.summary.groupTuple(by: [0, 1])
    mergeMetrics(metrics_in)
    // Join the summary metrics with the VCF stats to have a comprehensive input for the MultiQC report
    multiqc_in = sompyBenchmark.out.summary
        .groupTuple(by: [0, 1])
        .join(vcfStats.out.stats.groupTuple(by: [0, 1]), by: [0, 1])
    multiQCreports(multiqc_in)
}
