/*
==================================================================================================================================
# VarDict SOMATIC VARIANT CALLING PIPELINE
==================================================================================================================================
# This script calls somatic SNVs and InDels using the VarDict variant caller by:
# 1. Calling variants with VarDict-Java: variants are called in normal-tumor pairs, defining sample B as normal 
#    and samples D and E as tumoral. Therefore, variant calling is performed for B-D and B-E pairs.
#    -G ${fa_file}: indicates path to chromosome 7 FASTA sequence
#    -f ${af_threshold}: allele frequency threshold for variant calling
#    -N ${tumor_sample}: indicates path to tumor sample alignments (D or E)
#    -b "${tumor_bam}|${normal_bam}": indicates path to tumor and normal sample alignments (D or E and B, respectively)
#    -c 1 -S 2 -E 3: indicates the columns in the input BAM file corresponding to chromosome, start and end positions, respectively
# 2. Filtering only somatic "PASS" variants with bcftools: raw VCF files generated by VarDict are filtered to retain only 
#    variants that are classified as "Somatic" and have a "PASS" filter status. The resulting VCF file is indexed for downstream analyses

# For each step, a specific Seqera container (compatible with bioconda and arm64/linux) has been used
# ==================================================================================================================================
*/

nextflow.enable.dsl=2

/*
 * Workflow Input Parameters
 */

// Path to the main project directory
params.project = "/Users/nairaramosandres/Benchmarking-Somatic-VariantCallers-ctDNA"
// Path to aligned reads with marked duplicates
params.aligned_reads_bam = "${params.project}/results/Results_Subsample_*/mark_duplicates/duplicates_alignments/*.bam"
// Path to Chromosome 7 reference FASTA and its corresponding index files
params.genome ="${params.project}/genome/chr7_genome/chr7.fa"
// Path to Onco Panel bed files from Chromosome 7
params.bed = "${params.project}/metadata/bed_files/chr7_target.bed"
// Path to the main results directory
params.outdir = "${params.project}/results"


/*
 * Workflow Processes
 */

// 1. Calling somatic SNVs and InDels with VarDict-Java
process vardictSomaticVC {

    tag {"Variant Calling ${normal_sample} and ${tumor_sample} with VarDict Somatic"}
    container 'community.wave.seqera.io/library/vardict-java:1.8.3--675bbcc5303f55d1'
    publishDir "${params.outdir}/Results_Subsample_*/variant_calling/vardict_vcf", mode: 'copy'
 
    input:
    tuple val(subsample_id), val(normal_sample), path(normal_bam), path(normal_bai), val(tumor_sample), path(tumor_bam), path(tumor_bai)
    path fa_file
    path fai_file
    path bed_file

    output:
    tuple val(subsample_id), val(normal_sample), val(tumor_sample), path("*_raw.vcf"), emit: vcf_group
    path("*.log"), emit: log_out
    
    script:
    // Define the output directory name
    def vcf_prefix = "${subsample_id}_${normal_sample}_vs_${tumor_sample}"
    // Define allele frequency threshold for variant calling
    def af_threshold = 0.01
    
    """
    # Create a temporary directory for R package installation necessary for testsomatic.R
    mkdir -p getopt_temp
    Rscript -e "install.packages('getopt', repos='https://cloud.r-project.org', lib='getopt_temp')"
    export R_LIBS_USER=\$(pwd)/getopt_temp
    
    # Run VarDict-Java for somatic variant calling, followed by statistical validation and VCF generation
    vardict-java \\
        -G ${fa_file} \\
        -f ${af_threshold} \\
        -N "${tumor_sample}" \\
        -b "${tumor_bam}|${normal_bam}" \\
        -c 1 -S 2 -E 3 ${bed_file} \\
    | testsomatic.R \\
    | var2vcf_paired.pl -N "${tumor_sample}|${normal_sample}" -f ${af_threshold} \\
    > ${vcf_prefix}_raw.vcf 2> ${vcf_prefix}.log

    # Remove temporary directory
    rm -rf getopt_temp
    """
}

// 2. Filtering only somatic "PASS" variants with bcftools and indexing the output with bcftools
process bcftoolsIndexVariants {

    tag {"Indexing ${normal_sample} and ${tumor_sample} variants with bcftools"}
    container 'community.wave.seqera.io/library/bcftools:1.23.1--15a480527db1d585'
    publishDir "${params.outdir}/Results_Subsample_*/variant_calling/benchmarking_vcf", mode: 'copy'
 
    input:
    tuple val(subsample_id), val(normal_sample), val(tumor_sample), path(vcf_file)

    output:
    tuple val(subsample_id), path("*.vcf.gz*"), emit: vardict_final_indexed
    
    script:
    def indexed_prefix = "${subsample_id}_${normal_sample}_vs_${tumor_sample}_vardict_final.vcf.gz"
    """
    # Retain only variants with 'Somatic' status and 'PASS' filter status and index the resulting VCF file
    bcftools filter -i 'STATUS ~ "Somatic" && FILTER == "PASS"' ${vcf_file} -Oz -o ${indexed_prefix}
    bcftools index -c ${indexed_prefix}
    """
}

/*
 * Workflow
 */

workflow {

    // Channel for aligned .bam/.bai files wth marked duplicates for each Subsample 1, 3 and 5
    alignment_ch = Channel.fromPath(params.aligned_reads_bam, checkIfExists: true)
        .map { file -> 
            def sub_id = file.parent.parent.parent.name.replace("Results_Subsample_", "S")
            def duplicates_id = file.name.take(file.name.lastIndexOf('.'))
            def sample_id = duplicates_id.replace("_duplicates", "")
            def type = file.name.take(1)
            return tuple(sub_id, type, sample_id, file, file + ".bai")
        }

    // Channel for Normal samples (B)
    normal_sample_ch = alignment_ch
        .filter { it[1] == 'B' }
        .map { tuple(it[0], it[2], it[3], it[4]) }

    // Channel for Normal samples (D/E)
    tumor_sample_ch = alignment_ch
        .filter { it[1] != 'B' }
        .map { tuple(it[0], it[2], it[3], it[4]) }

    // Pair normal and tumor samples by their Subsample ID
    paired_samples_ch = normal_sample_ch.cross(tumor_sample_ch)
        .map { n, t -> 
            return tuple(n[0], n[1], n[2], n[3], t[1], t[2], t[3])
        }
    // Channel for Chromosome 7 reference FASTA and all index files
    genome_ch = Channel.fromPath(params.genome, checkIfExists: true).collect()
    fai_ch    = Channel.fromPath("${params.genome}.fai", checkIfExists: true).collect()
    // Channel for Onco Panel BED file
    bed_ch    = Channel.fromPath(params.bed, checkIfExists: true).collect()

    // Processes execution
    vardictSomaticVC(paired_samples_ch, genome_ch, fai_ch, bed_ch)
    bcftoolsIndexVariants(vardictSomaticVC.out.vcf_group)
}